[project]
name = "somethingtodo-today-api"
version = "0.0.1"
description = "API for somethingtodo-today app"
readme = "README.md"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.128.5",
    "pydantic>=2.12.5",
]
requires-python = ">= 3.14"
